### ISSUE TITLE
master is not building

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#536]
Looks like `v7.h` and `v7.c` are out of sync?

![image](https://cloud.githubusercontent.com/assets/627915/11645069/1f6088ea-9d06-11e5-8254-327735d13187.png)

**Comment by mmikulicic** [comment]
should be fixed, PTAL

**Comment by swisspol** [comment]
Wait, wait, it's not fixed (ignore the ffi warning, this one is my stuff):

![image](https://cloud.githubusercontent.com/assets/627915/11646678/38ba6c0c-9d15-11e5-8e44-fd2b78397b46.png)

**Comment by mmikulicic** [comment]
ok, this is a different issue. Seems to be C++ specific but I cannot reproduce.

Could you share the exact list of build flags you're using ?

---

main.cc:
```c++
#include "v7.h"

int main() {
  struct v7* v7= v7_create();
  v7_val_t v;
  v7_exec(v7, "1+2", &v);
  v7_println(v7, v);
  return 0;
}

```

```sh
$ clang++ -c main.cc && clang -c v7.c && clang++ -o repro main.o v7.o && ./repro
3
```

Built at sha 927a946

**Comment by swisspol** [comment]
I'm compiling `v7.c` using an Xcode project so it's compiled as a C file, not a C++ file. That said, `v7.h` is included in a `.mm` file (ObjC++) and the APIs are only used there.

```
CompileC /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Objects-normal-asan/x86_64/v7.o /Users/pol/Downloads/Cross/v7/v7.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/pol/Downloads/Cross/Mac
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fmodules -gmodules -fmodules-cache-path=/Users/pol/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fmodules-ignore-macro=V7_NO_FS -fbuild-session-file=/Users/pol/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.8 -g -fvisibility=hidden -Wno-sign-conversion -fsanitize=address -iquote /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Cross-generated-files.hmap -I/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Cross-own-target-headers.hmap -I/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Cross-all-target-headers.hmap -iquote /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Cross-project-headers.hmap -I/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Products/Debug/include -I../libffi/macosx/include -I../_App_/Source -I/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/DerivedSources/x86_64 -I/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/DerivedSources -F/Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Products/Debug -Wno-unreachable-code -DV7_NO_FS -MMD -MT dependencies -MF /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Objects-normal-asan/x86_64/v7.d --serialize-diagnostics /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Objects-normal-asan/x86_64/v7.dia -c /Users/pol/Downloads/Cross/v7/v7.c -o /Users/pol/Library/Developer/Xcode/DerivedData/Cross-emtkntpomxtevegmfquubmsyhpqe/Build/Intermediates/Cross.build/Debug/Cross.build/Objects-normal-asan/x86_64/v7.o

/Users/pol/Downloads/Cross/v7/v7.c:16409:24: warning: unused function 'i_apply' [-Wunused-function]
V7_PRIVATE enum v7_err i_apply(struct v7 *v7, v7_val_t *volatile result,
                       ^
/Users/pol/Downloads/Cross/v7/v7.c:3274:24: warning: function 'apply_private' has internal linkage but is not defined [-Wundefined-internal]
V7_PRIVATE enum v7_err apply_private(struct v7 *v7, v7_val_t *volatile result,
                       ^
/Users/pol/Downloads/Cross/v7/v7.c:9752:7: note: used here
      apply_private(v7, &val, func, v, V7_UNDEFINED, 0);
      ^
2 warnings generated.
```

**Comment by swisspol** [comment]
Found it! The compile failure is due to `-DV7_NO_FS`.

**Comment by mmikulicic** [comment]
Thanks for spotting this, fixed in the dev branch pending internal review.

This shouldn't block you. `V7_NO_FS` is intended for embedded platforms that don't have fopen/fread and friends. Is there any reason you wanted to disable it ?

**Comment by swisspol** [comment]
2 reasons:
- I want to sandbox the JS runtime in my app as much as possible and this includes accessing the file system
- It doesn't build on WinRT - see #522 and #520

**Comment by mmikulicic** [comment]
`V7_NO_FS` disables C api that uses the filesytem, e.g. v7_exec_file

`V7_ENABLE_FILE` governs the FS access from JS code. File system access from JS code is disabled by default, you need to enable it explicitly.

**Comment by swisspol** [comment]
Ah good, to know, thanks! In any I typically disable features I don't need when using 3rd party libraries and I have no need for v7 JS or C APIs that touch the file system in any way.,

**Comment by mmikulicic** [comment]
yeah, our defaults are quite conservative. If you see an ENABLE_SOMETHING flag it means it's disabled by default.

https://www.cesanta.com/developer/v7#_build_options

We also provide three build profiles, but these are mainly targeted at embedded targets as they might disable very useful functionality such as regexp or utf8.

We probably should prefix low level flags with something like "PLATFORM'
